services:
  # Serviço PHP/Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - erp_network
    depends_on:
      - db
      - redis

  # Serviço Nginx
  nginx:
    image: nginx:alpine
    container_name: erp_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - erp_network
    depends_on:
      - app

  # Serviço MySQL
  db:
    image: mysql:8.0
    container_name: erp_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - erp_network

  # Serviço Redis
  redis:
    image: redis:alpine
    container_name: erp_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - erp_network

networks:
  erp_network:
    driver: bridge

volumes:
  dbdata:
    driver: local 