# Docker Compose para SigStore ERP
# Configurado para resolver problemas de permissão e versão obsoleta
# UID e GID são definidos no arquivo .env para evitar problemas de permissão

services:
  # Serviço PHP/Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: sigstore_app
    restart: unless-stopped
    working_dir: /var/www
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - erp_network
    depends_on:
      - db
      - redis

  # Serviço Nginx
  nginx:
    image: nginx:alpine
    container_name: sigstore_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - erp_network
    depends_on:
      - app

  # Serviço MySQL
  db:
    image: mysql:8.0
    container_name: sigstore_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sigstore
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: sigstore
      MYSQL_PASSWORD: sigstore123
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - erp_network

  # Serviço Redis
  redis:
    image: redis:alpine
    container_name: sigstore_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - erp_network

volumes:
  dbdata:

networks:
  erp_network:
    driver: bridge 